# These two are mutually exclusive
# The two can't be set to 'yes' or 'no' at the same time
general:
    use_autopilot: no
    use_manual: yes

ultrasonic_sensors:
    min_distance_allowed: 30
    sensors:
            #    - sensor1:
            # trigger: 5
            # echo: 6
            # led: 'front'
    # - sensor2:
    #       trigger: 9
    #       echo: 12
    #       led: 'right'
        - sensor1:
            trigger: 7
            echo: 22
            led: 'left'
        - sensor2:
            trigger: 17
            echo: 27
            led: 'back'
        - sensor3:
            trigger: 24
            echo: 25
            led: 'diag_pos'
        - sensor4:
            trigger: 18
            echo: 23
            led: 'diag_neg'

motors:
    pin_s1: 4
    pin_s2: 5
    pin_brake: 2

offline_voice:
    motor_power: 40
    models:
        stop_model: 'OfflineVoice/resources/models/parar.pmdl'
        forward_model: 'OfflineVoice/resources/models/adelante.pmdl'
        left_model: 'OfflineVoice/resources/models/izquierda.pmdl'
        right_model: 'OfflineVoice/resources/models/derecha.pmdl'
        backwards_model: 'OfflineVoice/resources/models/atras.pmdl'
